#!/bin/bash

SRC=(tests/main.cpp tar.cpp)

OUT_DIR=out
OUT=$OUT_DIR/tar_tests
CMD=`python .ycm_extra_conf.py compile-flags`

# For debugging
echo "Running clang with these flags:"
echo $CMD

mkdir -p $OUT_DIR

clang++ $CMD ${SRC[*]} -o $OUT

